fix the pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -513,13 +513,17 @@ configure_system_tests:
     SYSTEM_TESTS_LIBRARY: auto_inject
     S3_AGENT_LINUX_INSTALL_SCRIPT_BUCKET: system-tests-aws-agent-linux-install-script
   script:
-    - echo "DEBUG ARTIFACTS FROM generate-scripts"
-    - ls -la
-    - echo "END DEBUG ARTIFACTS FROM generate-scripts"
-    - echo "Uploading the installer script to S3..."
-    - S3_DESTINATION="s3://${S3_AGENT_LINUX_INSTALL_SCRIPT_BUCKET}/${CI_PIPELINE_ID}/"
-    - echo "S3 destination: ${S3_DESTINATION}"
-    - aws s3 cp install_script_agent7.sh "$S3_DESTINATION" --recursive --quiet || echo "Failed to upload the installer script to S3"
+    - |
+      echo "DEBUG ARTIFACTS FROM generate-scripts"
+      ls -la
+      echo "DEBUG ARTIFACTS FROM generate-scripts"
+      ls -la
+      echo "END DEBUG ARTIFACTS FROM generate-scripts"
+      echo "Uploading the installer script to S3..."
+      S3_DESTINATION="s3://${S3_AGENT_LINUX_INSTALL_SCRIPT_BUCKET}/${CI_PIPELINE_ID}/"
+      echo "S3 destination: ${S3_DESTINATION}"
+      aws s3 cp install_script_agent7.sh "$S3_DESTINATION" --recursive --quiet || echo "Failed to upload the installer script to S3"
+      echo "END UPLOADING THE INSTALLER SCRIPT TO S3"
     - cd /system-tests
     - git pull  # update to most recent system-tests
     - git checkout $SYSTEM_TESTS_REF
