Also fix zypper failures on broken repos when installing agent

diff --git a/install_script.sh.template b/install_script.sh.template
--- a/install_script.sh.template
+++ b/install_script.sh.template
@@ -557,7 +557,7 @@ elif [ "$OS" = "SUSE" ]; then
       $sudo_cmd ZYPP_RPM_DEBUG="${ZYPP_RPM_DEBUG:-0}" zypper --non-interactive install curl ||:
     fi
     if ! rpm -q curl > /dev/null; then
-      echo -e "\033[31mAPI key not available in DD_API_KEY environment variable.\033[0m\n"
+      echo -e "\033[31mFailed to install curl.\033[0m\n"
     fi
   fi
 
@@ -656,10 +656,18 @@ elif [ "$OS" = "SUSE" ]; then
   fi
 
   if [ -z "$sudo_cmd" ]; then
-    ZYPP_RPM_DEBUG="${ZYPP_RPM_DEBUG:-0}" zypper --non-interactive install "${packages[@]}"
+    ZYPP_RPM_DEBUG="${ZYPP_RPM_DEBUG:-0}" zypper --non-interactive install "${packages[@]}" ||:
   else
-    $sudo_cmd ZYPP_RPM_DEBUG="${ZYPP_RPM_DEBUG:-0}" zypper --non-interactive install "${packages[@]}"
+    $sudo_cmd ZYPP_RPM_DEBUG="${ZYPP_RPM_DEBUG:-0}" zypper --non-interactive install "${packages[@]}" ||:
   fi
+
+  # If zypper fails to refresh a random repo, it installs the package, but then fails
+  # anyway. Therefore we let it do its thing and then see if curl was installed or not.
+  for expected_pkg in "${packages[@]}"; do
+    if ! rpm -q "${expected_pkg}" > /dev/null; then
+      echo -e "\033[31mFailed to install ${expected_pkg}.\033[0m\n"
+    fi
+  done
 
 else
     printf "\033[31mYour OS or distribution are not supported by this install script.
