Fix APM variable names and behavior (#49)
* DD_APM_INSTRUMENTATION_ENABLED now has 3 values: all,docker,host. DD_APM_LIBRARIES renamed to DD_APM_INSTRUMENTATION_LANGUAGES.

* Add DD_APM_INSTRUMENTATION_NO_CONFIG_CHANGE

* Fix error message with obsolete advice.

diff --git a/install_script.sh.template b/install_script.sh.template
--- a/install_script.sh.template
+++ b/install_script.sh.template
@@ -355,25 +355,33 @@ if [ -n "$DD_FIPS_MODE" ]; then
 fi
 
 declare -a apm_libraries
+declare host_injection_enabled
+declare docker_injection_enabled
 
-host_injection_enabled=
-if [[ "$DD_APM_HOST_INJECTION_ENABLED" == "true" || ( -z "$DD_APM_HOST_INJECTION_ENABLED" && "$DD_APM_INSTRUMENTATION_ENABLED" == "true") ]] ; then
-  if [ "$no_agent" ]; then
-      ERROR_MESSAGE="Host injection is not supported with the DD_NO_AGENT_INSTALL flag. Disable host injection with DD_APM_HOST_INJECTION_ENABLED=false or unset DD_NO_AGENT_INSTALL"
-      ERROR_CODE=$INVALID_PARAMETERS_CODE
-      echo -e "\033[31m$ERROR_MESSAGE\033[0m\n"
-      report_telemetry
-      exit 1;
-  fi
-
+if [ "$DD_APM_INSTRUMENTATION_ENABLED" = "all" ] ; then
   host_injection_enabled="true"
-  apm_libraries=("datadog-apm-inject")
+  docker_injection_enabled="true"
 fi
 
-docker_injection_enabled=
-if [[ "$DD_APM_DOCKER_INJECTION_ENABLED" == "true" || ( -z "$DD_APM_DOCKER_INJECTION_ENABLED" && "$DD_APM_INSTRUMENTATION_ENABLED" == "true") ]] ; then
+if [ "$DD_APM_INSTRUMENTATION_ENABLED" = "host" ] ; then
+  host_injection_enabled="true"
+fi
+
+if [ "$DD_APM_INSTRUMENTATION_ENABLED" = "docker" ] ; then
   docker_injection_enabled="true"
-  apm_libraries=("datadog-apm-inject")
+  no_agent=true
+fi
+
+if [ -n "${host_injection_enabled}${docker_injection_enabled}" ] ; then
+    apm_libraries=("datadog-apm-inject")
+fi
+
+if [ -n "${host_injection_enabled}" ] && [ -n "${no_agent}" ] ; then
+    ERROR_MESSAGE="Host injection is not supported with the DD_NO_AGENT_INSTALL flag. Unset either DD_APM_INSTRUMENTATION_ENABLED or DD_NO_AGENT_INSTALL"
+    ERROR_CODE=$INVALID_PARAMETERS_CODE
+    echo -e "\033[31m$ERROR_MESSAGE\033[0m\n"
+    report_telemetry
+    exit 1;
 fi
 
 daemon_config_dir="/etc/docker"
@@ -388,8 +396,8 @@ if [ -n "$docker_injection_enabled" ]; then
     fi
 fi
 
-if [ -n "$DD_APM_LIBRARIES" ]; then
-  read -r -a lib_array <<< "$DD_APM_LIBRARIES"
+if [ -n "$DD_APM_INSTRUMENTATION_LANGUAGES" ]; then
+  read -r -a lib_array <<< "$DD_APM_INSTRUMENTATION_LANGUAGES"
   for lib in "${lib_array[@]}"
   do
     case $lib in
@@ -420,6 +428,11 @@ if [ -n "$DD_APM_LIBRARIES" ]; then
 elif [ -n "$host_injection_enabled" ] || [ -n "$docker_injection_enabled" ]; then
   # Default to all libraries if injection is enabled
   apm_libraries+=("datadog-apm-library-all")
+fi
+
+no_config_change=
+if [ -n "$DD_APM_INSTRUMENTATION_NO_CONFIG_CHANGE" ]; then
+  no_config_change="--no-config-change"
 fi
 
 system_probe_ensure_config=
@@ -1101,7 +1114,7 @@ fi
 
 # run apm injection scripts
 if [ -n "$host_injection_enabled" ]; then
-  $sudo_cmd dd-host-install --no-agent-restart
+  $sudo_cmd dd-host-install --no-agent-restart ${no_config_change}
 fi
 
 if [ -n "$docker_injection_enabled" ]; then
