Extend usage of 'ensure_config_file_exists'
Merge create_config_file and ensure_file_exists

diff --git a/install_script.sh.template b/install_script.sh.template
--- a/install_script.sh.template
+++ b/install_script.sh.template
@@ -169,7 +169,7 @@ function on_error() {
 
     printf "\033[31m$ERROR_MESSAGE
 It looks like you hit an issue when trying to install the $nice_flavor.
-    
+
     $ERR_SUMMARY
 
 Troubleshooting and basic usage information for the $nice_flavor are available at:
@@ -239,19 +239,6 @@ function remove_rpm_gpg_keys() {
     done
 }
 
-function create_config_file() {
-    local sudo_cmd="$1"
-    local config_file="$2"
-    local owner="$3"
-
-    if [ ! -e "$config_file" ]; then
-        $sudo_cmd cp "$config_file.example" "$config_file"
-    fi
-
-    $sudo_cmd chown "$owner:dd-agent" "$config_file"
-    $sudo_cmd chmod 640 "$config_file"
-}
-
 function ensure_config_file_exists() {
     local sudo_cmd="$1"
     local config_file="$2"
@@ -259,8 +246,12 @@ function ensure_config_file_exists() {
 
     if [ -e "$config_file" ]; then
         printf "\033[34m\n* Keeping old $config_file configuration file\n\033[0m\n"
+        return 1
     else
-        create_config_file "$sudo_cmd" "$config_file" "$owner"
+        $sudo_cmd cp "$config_file.example" "$config_file"
+        $sudo_cmd chown "$owner:dd-agent" "$config_file"
+        $sudo_cmd chmod 640 "$config_file"
+        return 0
     fi
 }
 
@@ -774,7 +765,7 @@ if [ "$OS" == "RedHat" ]; then
     echo -e "  \033[33mInstalling package(s): ${packages[*]}\n\033[0m"
 
     $sudo_cmd yum -y --disablerepo='*' --enablerepo='datadog' install $dnf_flag "${packages[@]}" 2> >(tee /tmp/ddog_install_error_msg >&2) || $sudo_cmd yum -y install $dnf_flag "${packages[@]}" 2> >(tee /tmp/ddog_install_error_msg >&2)
-    
+
     ERR_SUMMARY=$(grep "Error Summary" -A3 /tmp/ddog_install_error_msg || true)
 
 elif [ "$OS" == "Debian" ]; then
@@ -893,7 +884,7 @@ If the cause is unclear, please contact Datadog support.
     echo -e "  \033[33mInstalling package(s): ${packages[*]}\n\033[0m"
 
     $sudo_cmd apt-get install -y --force-yes "${packages[@]}" 2> >(tee /tmp/ddog_install_error_msg >&2)
-    
+
     ERR_SUMMARY=$(grep "No space left on device" -C1 /tmp/ddog_install_error_msg || true)
 
     ERROR_MESSAGE=""
@@ -1090,35 +1081,33 @@ fi
 if [ -e "$config_file" ] && [ -z "$upgrade" ]; then
   printf "\033[34m\n* Keeping old $config_file configuration file\n\033[0m\n"
 elif [ ! "$no_agent" ]; then
-  if [ ! -e "$config_file" ]; then
-    $sudo_cmd cp "$config_file.example" "$config_file"
-  fi
-  if [ -n "$apikey" ]; then
-    printf "\033[34m\n* Adding your API key to the $nice_flavor configuration: $config_file\n\033[0m\n"
-    $sudo_cmd sh -c "sed -i 's/api_key:.*/api_key: $apikey/' $config_file"
-  else
-    # If the import script failed for any reason, we might end here also in case
-    # of upgrade, let's not start the agent or it would fail because the api key
-    # is missing
-    if ! $sudo_cmd grep -q -E '^api_key: .+' "$config_file"; then
-      printf "\033[31mThe $nice_flavor won't start automatically at the end of the script because the Api key is missing, please add one in datadog.yaml and start the $nice_flavor manually.\n\033[0m\n"
-      no_start=true
+  if ensure_config_file_exists "$sudo_cmd" "$config_file" "dd-agent"; then
+    if [ -n "$apikey" ]; then
+      printf "\033[34m\n* Adding your API key to the $nice_flavor configuration: $config_file\n\033[0m\n"
+      $sudo_cmd sh -c "sed -i 's/api_key:.*/api_key: $apikey/' $config_file"
+    else
+      # If the import script failed for any reason, we might end here also in case
+      # of upgrade, let's not start the agent or it would fail because the api key
+      # is missing
+      if ! $sudo_cmd grep -q -E '^api_key: .+' "$config_file"; then
+        printf "\033[31mThe $nice_flavor won't start automatically at the end of the script because the Api key is missing, please add one in datadog.yaml and start the $nice_flavor manually.\n\033[0m\n"
+        no_start=true
+      fi
     fi
-  fi
 
-  if [ -z "$fips_mode" ]; then
-    if [ -n "$site" ]; then
-      printf "\033[34m\n* Setting SITE in the $nice_flavor configuration: $config_file\n\033[0m\n"
-      $sudo_cmd sh -c "sed -i 's/# site:.*/site: $site/' $config_file"
-    fi
-    if [ -n "$DD_URL" ]; then
-      printf "\033[34m\n* Setting DD_URL in the $nice_flavor configuration: $config_file\n\033[0m\n"
-      $sudo_cmd sh -c "sed -i 's|# dd_url:.*|dd_url: $DD_URL|' $config_file"
-    fi
-  else
-    printf "\033[34m\n* Setting $nice_flavor configuration to use FIPS proxy: $config_file\n\033[0m\n"
-    $sudo_cmd cp "$config_file" "${config_file}.orig"
-    $sudo_cmd sh -c "exec cat - '${config_file}.orig' > '$config_file'" <<EOF
+    if [ -z "$fips_mode" ]; then
+      if [ -n "$site" ]; then
+        printf "\033[34m\n* Setting SITE in the $nice_flavor configuration: $config_file\n\033[0m\n"
+        $sudo_cmd sh -c "sed -i 's/# site:.*/site: $site/' $config_file"
+      fi
+      if [ -n "$DD_URL" ]; then
+        printf "\033[34m\n* Setting DD_URL in the $nice_flavor configuration: $config_file\n\033[0m\n"
+        $sudo_cmd sh -c "sed -i 's|# dd_url:.*|dd_url: $DD_URL|' $config_file"
+      fi
+    else
+      printf "\033[34m\n* Setting $nice_flavor configuration to use FIPS proxy: $config_file\n\033[0m\n"
+      $sudo_cmd cp "$config_file" "${config_file}.orig"
+      $sudo_cmd sh -c "exec cat - '${config_file}.orig' > '$config_file'" <<EOF
 # Configuration for the agent to use datadog-fips-proxy to communicate with Datadog via FIPS-compliant channel.
 
 fips:
@@ -1126,15 +1115,16 @@ fips:
     port_range_start: 9803
     https: false
 EOF
-  fi
-  if [ -n "$hostname" ]; then
-    printf "\033[34m\n* Adding your HOSTNAME to the $nice_flavor configuration: $config_file\n\033[0m\n"
-    $sudo_cmd sh -c "sed -i 's/# hostname:.*/hostname: $hostname/' $config_file"
-  fi
-  if [ -n "$host_tags" ]; then
-      printf "\033[34m\n* Adding your HOST TAGS to the $nice_flavor configuration: $config_file\n\033[0m\n"
-      formatted_host_tags="['""$( echo "$host_tags" | sed "s/,/','/g" )""']"  # format `env:prod,foo:bar` to yaml-compliant `['env:prod','foo:bar']`
-      $sudo_cmd sh -c "sed -i \"s/^# tags:.*/tags: ""$formatted_host_tags""/\" $config_file"
+    fi
+    if [ -n "$hostname" ]; then
+      printf "\033[34m\n* Adding your HOSTNAME to the $nice_flavor configuration: $config_file\n\033[0m\n"
+      $sudo_cmd sh -c "sed -i 's/# hostname:.*/hostname: $hostname/' $config_file"
+    fi
+    if [ -n "$host_tags" ]; then
+        printf "\033[34m\n* Adding your HOST TAGS to the $nice_flavor configuration: $config_file\n\033[0m\n"
+        formatted_host_tags="['""$( echo "$host_tags" | sed "s/,/','/g" )""']"  # format `env:prod,foo:bar` to yaml-compliant `['env:prod','foo:bar']`
+        $sudo_cmd sh -c "sed -i \"s/^# tags:.*/tags: ""$formatted_host_tags""/\" $config_file"
+    fi
   fi
   if [ -n "$dd_env" ]; then
     printf "\033[34m\n* Adding your DD_ENV to the $nice_flavor configuration: $config_file\n\033[0m\n"
@@ -1142,20 +1132,23 @@ EOF
   fi
 
   if [ "$DD_RUNTIME_SECURITY_CONFIG_ENABLED" == "true" ]; then
-    ensure_config_file_exists "$sudo_cmd" "$system_probe_config_file" "root"
-    ensure_config_file_exists "$sudo_cmd" "$security_agent_config_file" "root"
+    if ensure_config_file_exists "$sudo_cmd" "$system_probe_config_file" "root"; then
+      printf "\033[34m\n* Enabling runtime security in system_probe configuration\n\033[0m\n"
+      $sudo_cmd sh -c "sed -i 's/^#\s*runtime_security_config:/runtime_security_config:/' $security_agent_config_file $system_probe_config_file"
+    fi
 
-    printf "\033[34m\n* Enabling runtime security in configuration\n\033[0m\n"
-    $sudo_cmd sh -c "sed -i 's/^#\s*runtime_security_config:/runtime_security_config:/' $security_agent_config_file $system_probe_config_file"
-    $sudo_cmd sh -c "sed -i '/^runtime_security_config:/,// s/\(\s\+\)#\s*enabled:\s*false/\1enabled: true/' $security_agent_config_file $system_probe_config_file"
+    if ensure_config_file_exists "$sudo_cmd" "$security_agent_config_file" "root"; then
+      printf "\033[34m\n* Enabling runtime security in security_agent configuration\n\033[0m\n"
+      $sudo_cmd sh -c "sed -i '/^runtime_security_config:/,// s/\(\s\+\)#\s*enabled:\s*false/\1enabled: true/' $security_agent_config_file $system_probe_config_file"
+    fi
   fi
 
   if [ "$DD_COMPLIANCE_CONFIG_ENABLED" == "true" ]; then
-    ensure_config_file_exists "$sudo_cmd" "$security_agent_config_file" "root"
-
-    printf "\033[34m\n* Enabling compliance monitoring in configuration\n\033[0m\n"
-    $sudo_cmd sh -c "sed -i 's/^#\s*compliance_config:/compliance_config:/' $security_agent_config_file"
-    $sudo_cmd sh -c "sed -i '/^compliance_config:/,// s/\(\s\+\)#\s*enabled:\s*false/\1enabled: true/' $security_agent_config_file"
+    if ensure_config_file_exists "$sudo_cmd" "$security_agent_config_file" "root"; then
+      printf "\033[34m\n* Enabling compliance monitoring in security_agent configuration\n\033[0m\n"
+      $sudo_cmd sh -c "sed -i 's/^#\s*compliance_config:/compliance_config:/' $security_agent_config_file"
+      $sudo_cmd sh -c "sed -i '/^compliance_config:/,// s/\(\s\+\)#\s*enabled:\s*false/\1enabled: true/' $security_agent_config_file"
+    fi
   fi
 fi
 
