Finish updating install script

diff --git a/install_script.sh.template b/install_script.sh.template
--- a/install_script.sh.template
+++ b/install_script.sh.template
@@ -909,6 +909,7 @@ fi
 config_file_fips=$etcdirfips/datadog-fips-proxy.cfg
 system_probe_config_file=$etcdir/system-probe.yaml
 security_agent_config_file=$etcdir/security-agent.yaml
+otel_config_file=$etcdir/otel-config.yaml
 environment_file=/etc/environment
 dd_environment_file=/etc/datadog-agent/environment
 
@@ -978,13 +979,32 @@ else
   apt_repo_version="${agent_dist_channel} ${agent_major_version}"
 fi
 
-ddot=
+# Setup DDOT if enabled, the distribution channel for DDOT is independent from that of the core agent
+ddot_dist_channel=beta
+if [ -n "$DD_OTELCOLLECTOR_ENABLED" ] && [ -n "$DD_DDOT_DIST_CHANNEL" ]; then
+  if [ "$repository_url" == "datadoghq.com" ]; then
+    if [ "$DD_DDOT_DIST_CHANNEL" != "beta" ]; then
+      ERROR_MESSAGE="DD_DDOT_DIST_CHANNEL must be 'beta' while only available in preview. Current value: $DD_DDOT_DIST_CHANNEL"
+      ERROR_CODE=$INVALID_PARAMETERS_CODE
+      echo "$ERROR_MESSAGE"
+      report_telemetry
+      exit 1;
+    fi
+  elif [ "$DD_DDOT_DIST_CHANNEL" != "stable" ] && [ "$DD_DDOT_DIST_CHANNEL" != "beta" ] && [ "$DD_DDOT_DIST_CHANNEL" != "nightly" ]; then
+    ERROR_MESSAGE="DD_DDOT_DIST_CHANNEL must be either 'stable', 'beta' or 'nightly' on custom repos. Current value: $DD_DDOT_DIST_CHANNEL"
+    ERROR_CODE=$INVALID_PARAMETERS_CODE
+    echo "$ERROR_MESSAGE"
+    report_telemetry
+    exit 1;
+  fi
+  ddot_dist_channel=$DD_DDOT_DIST_CHANNEL
+fi
+
 ddot_yum_version_path=
 ddot_apt_repo_version=
-if [ -n "$DD_DDOT" ]; then
-  ddot=$DD_DDOT
-  ddot_yum_version_path="${ddot}/${agent_major_version}"
-  ddot_apt_repo_version="${ddot} ${agent_major_version}"
+if [ -n "$DD_OTELCOLLECTOR_ENABLED" ]; then
+  ddot_yum_version_path="${ddot_dist_channel}/${agent_major_version}"
+  ddot_apt_repo_version="${ddot_dist_channel} ${agent_major_version}"
 fi
 
 if [ ! "$apikey" ]; then
@@ -1157,8 +1177,8 @@ if [ "$OS" == "Red Hat" ]; then
     # if some packages were previously pinned (using excludepkgs)
     # this will unpin them as a side effect
     $sudo_cmd sh -c "echo -e '[datadog]\nname = Datadog, Inc.\nbaseurl = https://${yum_url}/${yum_version_path}/${ARCHI}/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=${rpm_repo_gpgcheck}\npriority=1\ngpgkey=${gpgkeys}' > /etc/yum.repos.d/datadog.repo"
-    if [ -n "$ddot" ]; then
-      $sudo_cmd sh -c "echo -e '[datadog]\nname = Datadog, Inc.\nbaseurl = https://${yum_url}/${ddot_yum_version_path}/${ARCHI}/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=${rpm_repo_gpgcheck}\npriority=1\ngpgkey=${gpgkeys}' > /etc/yum.repos.d/datadog-ddot.repo"
+    if [ -n "$DD_OTELCOLLECTOR_ENABLED" ]; then
+      $sudo_cmd sh -c "echo -e '[datadog-ddot]\nname = Datadog, Inc.\nbaseurl = https://${yum_url}/${ddot_yum_version_path}/${ARCHI}/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=${rpm_repo_gpgcheck}\npriority=1\ngpgkey=${gpgkeys}' > /etc/yum.repos.d/datadog-ddot.repo"
     fi
 
     $sudo_cmd yum -y clean metadata
@@ -1205,7 +1225,7 @@ if [ "$OS" == "Red Hat" ]; then
 
       # yum has a default retry of 10 https://github.com/Distrotech/yum/blob/f4e54aeed297158c563828aa3ebb93d0c8ce7e38/docs/yum.conf.5#L364-L366
       $sudo_cmd bash -c "SYSTEMD_OFFLINE=${SYSTEMD_OFFLINE:-0} yum -y --disablerepo='*' --enablerepo='datadog' install $dnf_flag ${packages[*]}" 2> >($sudo_cmd tee /tmp/ddog_install_error_msg >&2) || $sudo_cmd bash -c "SYSTEMD_OFFLINE=${SYSTEMD_OFFLINE:-0} yum -y install $dnf_flag ${packages[*]}" 2> >($sudo_cmd tee /tmp/ddog_install_error_msg >&2)
-      if [ -n "$ddot" ]; then
+      if [ -n "$DD_OTELCOLLECTOR_ENABLED" ]; then
         $sudo_cmd bash -c "SYSTEMD_OFFLINE=${SYSTEMD_OFFLINE:-0} yum -y --disablerepo='*' --enablerepo='datadog-ddot' install $dnf_flag datadog-agent-ddot" 2> >($sudo_cmd tee /tmp/ddog_install_error_msg >&2) || $sudo_cmd bash -c "SYSTEMD_OFFLINE=${SYSTEMD_OFFLINE:-0} yum -y install $dnf_flag datadog-agent-ddot" 2> >($sudo_cmd tee /tmp/ddog_install_error_msg >&2)
       fi
 
@@ -1270,7 +1290,7 @@ elif [ "$OS" == "Debian" ]; then
     $sudo_cmd sh -c "echo 'deb [signed-by=${apt_usr_share_keyring}] https://${apt_url}/ ${apt_repo_version}' > /etc/apt/sources.list.d/datadog.list"
     $sudo_cmd sh -c "chmod a+r /etc/apt/sources.list.d/datadog.list"
 
-    if [ -n "$ddot" ]; then
+    if [ -n "$DD_OTELCOLLECTOR_ENABLED" ]; then
       printf "\033[34m\n* Installing APT package sources for Datadog DDOT\n\033[0m\n"
       $sudo_cmd sh -c "echo 'deb [signed-by=${apt_usr_share_keyring}] https://${apt_url}/ ${ddot_apt_repo_version}' > /etc/apt/sources.list.d/datadog-ddot.list"
       $sudo_cmd sh -c "chmod a+r /etc/apt/sources.list.d/datadog-ddot.list"
@@ -1321,7 +1341,9 @@ If the failing repository is Datadog, please contact Datadog support.
 *****
 "
     $sudo_cmd apt-get update -o Dir::Etc::sourcelist="sources.list.d/datadog.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
-    $sudo_cmd apt-get update -o Dir::Etc::sourcelist="sources.list.d/datadog-ddot.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
+    if [ -n "$DD_OTELCOLLECTOR_ENABLED" ]; then
+      $sudo_cmd apt-get update -o Dir::Etc::sourcelist="sources.list.d/datadog-ddot.list" -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
+    fi
     ERROR_MESSAGE="ERROR
 Failed to install one or more packages, sometimes it may be
 due to another APT source failing. See the logs above to
@@ -1365,8 +1387,7 @@ If the cause is unclear, please contact Datadog support.
     $sudo_cmd chmod +x "${POLICYRCD}"
 
     $sudo_cmd bash -c "POLICYRCD='${POLICYRCD}' apt-get install -o Acquire::Retries='5' -y --force-yes ${packages[*]} 2> >($sudo_cmd tee /tmp/ddog_install_error_msg >&2)"
-    if [ -n "$ddot" ]; then
-      # TODO: I'm not sure if this would be correct since there's no repository specified in this command
+    if [ -n "$DD_OTELCOLLECTOR_ENABLED" ]; then
       $sudo_cmd bash -c "POLICYRCD='${POLICYRCD}' apt-get install -o Acquire::Retries='5' -y --force-yes datadog-agent-ddot 2> >($sudo_cmd tee /tmp/ddog_install_error_msg >&2)"
     fi
 
@@ -1448,9 +1469,17 @@ elif [ "$OS" == "SUSE" ]; then
 
   echo -e "\033[34m\n* Installing YUM Repository for Datadog\n\033[0m"
   $sudo_cmd sh -c "echo -e '[datadog]\nname=datadog\nenabled=1\nbaseurl=https://${yum_url}/suse/${yum_version_path}/${ARCHI}\ntype=rpm-md\ngpgcheck=1\nrepo_gpgcheck=${rpm_repo_gpgcheck}\ngpgkey=${gpgkeys}' > /etc/zypp/repos.d/datadog.repo"
+  if [ -n "$DD_OTELCOLLECTOR_ENABLED" ]; then
+    echo -e "\033[34m\n* Installing YUM Repository for DDOT\n\033[0m"
+    $sudo_cmd sh -c "echo -e '[datadog-ddot]\nname=datadog-ddot\nenabled=1\nbaseurl=https://${yum_url}/suse/${ddot_yum_version_path}/${ARCHI}\ntype=rpm-md\ngpgcheck=1\nrepo_gpgcheck=${rpm_repo_gpgcheck}\ngpgkey=${gpgkeys}' > /etc/zypp/repos.d/datadog-ddot.repo"
+  fi
+
 
   echo -e "\033[34m\n* Refreshing repositories\n\033[0m"
   $sudo_cmd zypper --non-interactive --no-gpg-checks refresh datadog
+  if [ -n "$DD_OTELCOLLECTOR_ENABLED" ]; then
+    $sudo_cmd zypper --non-interactive --no-gpg-checks refresh datadog-ddot
+  fi
 
   # ".32" is the latest version supported for OpenSUSE < 15 and SLES < 12
   # we explicitly test for SUSE11 = "yes", as some SUSE11 don't have /etc/os-release, thus SUSE_VER is empty
@@ -1521,6 +1550,14 @@ elif [ "$OS" == "SUSE" ]; then
       ZYPP_RPM_DEBUG="${ZYPP_RPM_DEBUG:-0}" SYSTEMD_OFFLINE=${SYSTEMD_OFFLINE:-0} zypper --non-interactive --no-refresh install "${packages[@]}" 2> >($sudo_cmd tee /tmp/ddog_install_error_msg >&2) ||:
     else
       $sudo_cmd ZYPP_RPM_DEBUG="${ZYPP_RPM_DEBUG:-0}" SYSTEMD_OFFLINE="${SYSTEMD_OFFLINE:-0}" zypper --non-interactive --no-refresh install "${packages[@]}" 2> >($sudo_cmd tee /tmp/ddog_install_error_msg >&2) ||:
+    fi
+
+    if [ -n "$DD_OTELCOLLECTOR_ENABLED" ]; then
+      if [ -z "$sudo_cmd" ]; then
+        ZYPP_RPM_DEBUG="${ZYPP_RPM_DEBUG:-0}" SYSTEMD_OFFLINE=${SYSTEMD_OFFLINE:-0} zypper --non-interactive --no-refresh install datadog-agent-ddot 2> >($sudo_cmd tee /tmp/ddog_install_error_msg >&2) ||:
+      else
+        $sudo_cmd ZYPP_RPM_DEBUG="${ZYPP_RPM_DEBUG:-0}" SYSTEMD_OFFLINE="${SYSTEMD_OFFLINE:-0}" zypper --non-interactive --no-refresh install datadog-agent-ddot 2> >($sudo_cmd tee /tmp/ddog_install_error_msg >&2) ||:
+      fi
     fi
 
     ERR_SUMMARY=$(grep "Write error" -C1 /tmp/ddog_install_error_msg || true)
@@ -1711,6 +1748,31 @@ discovery:
   enabled: true
 EOF
 }
+function update_ddot(){
+  local sudo_cmd="$1"
+  local config_file="$2"
+
+  if ! $sudo_cmd grep -q "^otelcollector:" "$config_file"; then
+    $sudo_cmd cp "$config_file" "${config_file}.orig"
+    $sudo_cmd sh -c "exec cat - '${config_file}.orig' > '$config_file'" <<EOF
+otelcollector:
+  enabled: true
+EOF
+  else
+    printf "\033[31m\n* otelcollector configuration already exists in $config_file, skipping the update.\n\033[0m\n"
+  fi
+
+  if ! $sudo_cmd grep -q "^agent_ipc:" "$config_file"; then
+    $sudo_cmd cp "$config_file" "${config_file}.orig"
+    $sudo_cmd sh -c "exec cat - '${config_file}.orig' > '$config_file'" <<EOF
+agent_ipc:
+  port: 5009
+  config_refresh_interval: 60
+EOF
+  else
+    printf "\033[31m\n* agent_ipc configuration already exists in $config_file, skipping the update.\n\033[0m\n"
+  fi
+}
 function manage_security_config(){
   local sudo_cmd="$1"
   local security_config_file="$2"
@@ -1772,6 +1834,15 @@ function manage_error_tracking_standalone_config(){
     set_in_env_file "$sudo_cmd" "$etc_environment" DD_CORE_AGENT_ENABLED "true"
   fi
 }
+function manage_otel_config(){
+  local sudo_cmd="$1"
+  local otel_config_file="$2"
+  local apikey="$3"
+  local site="$4"
+  if ensure_config_file_exists "$sudo_cmd" "$otel_config_file" "dd-agent"; then
+    $sudo_cmd sh -c "sed -i -e 's/\${env:DD_API_KEY}/$apikey/' -e 's/\${env:DD_SITE}/$site/'  $otel_config_file"
+  fi
+}
 # "Main" configuration update
 if [ -e "$config_file" ] && [ -z "$upgrade" ]; then
   printf "\033[34m\n* Keeping old $config_file configuration file\n\033[0m\n"
@@ -1793,6 +1864,12 @@ elif [ ! "$no_agent" ]; then
   fi
   manage_security_config "$sudo_cmd" "$security_agent_config_file" "$DD_RUNTIME_SECURITY_CONFIG_ENABLED" "$DD_COMPLIANCE_CONFIG_ENABLED"
   manage_system_probe_config "$sudo_cmd" "$system_probe_config_file" "$DD_RUNTIME_SECURITY_CONFIG_ENABLED" "$DD_DISCOVERY_ENABLED"
+fi
+
+# DDOT configuration update
+if [ -n "$DD_OTELCOLLECTOR_ENABLED" ]; then
+  update_ddot "$sudo_cmd" "$config_file"
+  manage_otel_config "$sudo_cmd" "$otel_config_file" "$apikey" "$site"
 fi
 
 if [ -e "$(dirname $dd_environment_file)" ]; then
