Revert DD_FIPS_MODE changes, keep datadog-fips-proxy, and remove packages only if the flavor is datadog-fips-agent

diff --git a/install_script.sh.template b/install_script.sh.template
--- a/install_script.sh.template
+++ b/install_script.sh.template
@@ -283,6 +283,9 @@ function getMapData() {
              "datadog-dogstatsd")
                 DATA="Datadog Dogstatsd"
                 ;;
+             "datadog-fips-proxy")
+                DATA="Datadog FIPS Proxy"
+                ;;
              "datadog-fips-agent")
                 DATA="Datadog FIPS Agent"
                 ;;
@@ -588,46 +591,44 @@ function install_installer() {
 }
 
 function remove_existing_packages_for_fips_flavor() {
-  local sudo_cmd="$1"
-  local os="$2"
-  local distribution="$3"
-  local packages_to_uninstall="$4"
+    local sudo_cmd="$1"
+    local os="$2"
 
-  local exit_status=0
-  # find if fips-proxy or existing agent is installed
-  if [ "$os" == "Debian" ]; then
-      $sudo_cmd apt list --installed "datadog-agent" "datadog-fips-proxy" 2>/dev/null | grep -q "datadog" || exit_status=$?
-  elif [ "$os" == "Red Hat" ]; then
-      $sudo_cmd yum list installed "datadog-agent" "datadog-fips-proxy" || exit_status=$?
-  elif [ "$os" == "SUSE" ]; then
-      $sudo_cmd zypper search -i "datadog-agent" "datadog-fips-proxy" || exit_status=$?
-  else
-      return 0
-  fi
+    local exit_status=0
+    # find if fips-proxy or existing agent is installed
+    if [ "$os" == "Debian" ]; then
+        $sudo_cmd apt list --installed "datadog-agent" "datadog-fips-proxy" 2>/dev/null | grep -q "datadog" || exit_status=$?
+    elif [ "$os" == "Red Hat" ]; then
+        $sudo_cmd yum list installed "datadog-agent" "datadog-fips-proxy" || exit_status=$?
+    elif [ "$os" == "SUSE" ]; then
+        $sudo_cmd zypper search -i "datadog-agent" "datadog-fips-proxy" || exit_status=$?
+    else
+        return 0
+    fi
 
-  if [ "$exit_status" -eq 0 ]; then
-      read -p "Found existing datadog-agent or datadog-fips-proxy installation. These packages will be removed for the datadog-fips-agent to be installed. Do you wish to continue? [y/N]: " -n 1 -r
-      if ! [[ $REPLY =~ ^[Yy]$ ]]; then
-          ERROR_MESSAGE="Unable to install datadog-fips-agent when existing datadog-agent or datadog-fips-proxy installed. Exiting."
-          ERROR_CODE=$INVALID_PARAMETERS_CODE
-          echo "$ERROR_MESSAGE"
-          report_telemetry
-          exit 1;
-      fi
-  else
-      return 0
-  fi
+    if [ "$exit_status" -eq 0 ]; then
+        read -p "Found existing datadog-agent or datadog-fips-proxy installation. These packages will be removed for the datadog-fips-agent to be installed. Do you wish to continue? [y/N]: " -n 1 -r
+        if ! [[ $REPLY =~ ^[Yy]$ ]]; then
+            ERROR_MESSAGE="Unable to install datadog-fips-agent when existing datadog-agent or datadog-fips-proxy installed. Exiting."
+            ERROR_CODE=$INVALID_PARAMETERS_CODE
+            echo "$ERROR_MESSAGE"
+            report_telemetry
+            exit 1;
+        fi
+    else
+        return 0
+    fi
 
-  echo -e "\033[34m\n* Removing the datadog-fips-proxy and existing datadog-agent packages\n\033[0m"
-  if [ "$os" == "Debian" ]; then
-      $sudo_cmd apt-get remove -y --force-yes "datadog-fips-proxy" "datadog-agent" || return $?
-  elif [ "$os" == "Red Hat" ]; then
-      $sudo_cmd yum -y --disablerepo='*' --enablerepo='datadog' remove "datadog-fips-proxy" "datadog-agent" || $sudo_cmd yum -y remove "datadog-fips-proxy" "datadog-agent" || return $?
-  elif [ "$os" == "SUSE" ]; then
-      $sudo_cmd zypper --non-interactive --no-refresh remove "datadog-fips-proxy" "datadog-agent" || return $?
-  else
-      return 0
-  fi
+    echo -e "\033[34m\n* Removing the datadog-fips-proxy and existing datadog-agent packages\n\033[0m"
+    if [ "$os" == "Debian" ]; then
+        $sudo_cmd apt-get remove -y --force-yes "datadog-fips-proxy" "datadog-agent" || return $?
+    elif [ "$os" == "Red Hat" ]; then
+        $sudo_cmd yum -y --disablerepo='*' --enablerepo='datadog' remove "datadog-fips-proxy" "datadog-agent" || $sudo_cmd yum -y remove "datadog-fips-proxy" "datadog-agent" || return $?
+    elif [ "$os" == "SUSE" ]; then
+        $sudo_cmd zypper --non-interactive --no-refresh remove "datadog-fips-proxy" "datadog-agent" || return $?
+    else
+        return 0
+    fi
 }
 
 echo -e "\033[34m\n* Datadog INSTALL_SCRIPT_REPORT_VERSION_PLACEHOLDER install script v${install_script_version}\n\033[0m"
@@ -686,6 +687,11 @@ if [ -n "$DD_UPGRADE" ]; then
   upgrade=$DD_UPGRADE
 fi
 
+fips_mode=
+if [ -n "$DD_FIPS_MODE" ]; then
+  fips_mode=$DD_FIPS_MODE
+fi
+
 error_tracking_standalone=
 if [ -n "$DD_APM_ERROR_TRACKING_STANDALONE" ]; then
   error_tracking_standalone=$DD_APM_ERROR_TRACKING_STANDALONE
@@ -704,21 +710,6 @@ fi
 agent_flavor="datadog-agent"
 if [ -n "$DD_AGENT_FLAVOR" ]; then
     agent_flavor=$DD_AGENT_FLAVOR #Eg: datadog-iot-agent
-fi
-
-fips_mode=
-if [ -n "$DD_FIPS_MODE" ]; then
-    fips_mode=$DD_FIPS_MODE
-    if [ -n "$DD_AGENT_FLAVOR" ] && [ "$DD_AGENT_FLAVOR" != "datadog-fips-agent" ]; then
-        # return error message
-        ERROR_MESSAGE="DD_FIPS_MODE sets the DD_AGENT_FLAVOR to the datadog-fips-agent but it is currently set to: $DD_AGENT_FLAVOR"
-        ERROR_CODE=$INVALID_PARAMETERS_CODE
-        echo "$ERROR_MESSAGE"
-        report_telemetry
-        exit 1;
-    else
-        agent_flavor="datadog-fips-agent"
-    fi
 fi
 
 datadog_installer=
@@ -838,6 +829,10 @@ else
   services=("$system_service")
 fi
 
+if [ -n "$fips_mode" ]; then
+  services+=("datadog-fips-proxy")
+fi
+
 if [ -n "$remote_updates" ]; then
   services+=("datadog-installer")
 fi
@@ -863,10 +858,13 @@ if [ -z "$etcdir" ]; then
     etcdir="/etc/datadog-agent"
 fi
 
+etcdirfips=/etc/datadog-fips-proxy
+
 if [ -z "$config_file" ]; then
     config_file="$etcdir/datadog.yaml"
 fi
 
+config_file_fips=$etcdirfips/datadog-fips-proxy.cfg
 system_probe_config_file=$etcdir/system-probe.yaml
 security_agent_config_file=$etcdir/security-agent.yaml
 environment_file=/etc/environment
@@ -1015,11 +1013,20 @@ if [ -n "$fips_mode" ]; then
         ERROR_CODE=$UNSUPPORTED_PLATFORM_CODE
         printf "\033[31m$ERROR_MESSAGE\033[0m\n"
         report_telemetry
+        exit 1;
+    fi
+    if [[ -n "$agent_minor_version_without_patch" ]] && [[ "${agent_minor_version_without_patch}" -lt 41 ]]; then
+        ERROR_MESSAGE="FIPS mode is only available since version AGENT_MAJOR_VERSION_PLACEHOLDER.41.0 and requested minor version is $agent_minor_version"
+        ERROR_CODE=$INVALID_PARAMETERS_CODE
+        printf "\033[31m$ERROR_MESSAGE\033[0m\n"
         report_telemetry
         exit 1;
     fi
+fi
+
+if [[ "$agent_flavor" == "datadog-fips-agent" ]]; then
     if [[ -n "$agent_minor_version_without_patch" ]] && [[ "${agent_minor_version_without_patch}" -lt 64 ]]; then
-        ERROR_MESSAGE="The datadog-fips-agent is only available since version 7.64.x and requested minor version is $agent_minor_version"
+        ERROR_MESSAGE="The datadog-fips-agent is only available since version AGENT_MAJOR_VERSION_PLACEHOLDER.64.x and requested minor version is $agent_minor_version"
         ERROR_CODE=$INVALID_PARAMETERS_CODE
         printf "\033[31m$ERROR_MESSAGE\033[0m\n"
         report_telemetry
@@ -1129,7 +1136,10 @@ if [ "$OS" == "Red Hat" ]; then
     # Install the installer
     # Note: this function will remove installed packages from the "packages" array
     install_installer "$sudo_cmd" "$OS" "$DISTRIBUTION" "$DD_INSTALLER" "$DD_REMOTE_UPDATES" "$DD_APM_INSTRUMENTATION_ENABLED" "packages" || true
-    remove_existing_packages_for_fips_flavor "$sudo_cmd" "$OS" "$DISTRIBUTION"
+
+    if [ "$agent_flavor" == "datadog-fips-agent" ]; then
+        remove_existing_packages_for_fips_flavor "$sudo_cmd" "$OS" "$DISTRIBUTION"
+    fi
 
     # packages can be empty if no_agent is set
     if [ ${#packages[@]} -ne 0 ]; then
@@ -1269,7 +1279,10 @@ If the cause is unclear, please contact Datadog support.
     # Install the installer
     # Note: this function will remove installed packages from the "packages" array
     install_installer "$sudo_cmd" "$OS" "$DISTRIBUTION" "$DD_INSTALLER" "$DD_REMOTE_UPDATES" "$DD_APM_INSTRUMENTATION_ENABLED" "packages" || true
-    remove_existing_packages_for_fips_flavor "$sudo_cmd" "$OS" "$DISTRIBUTION"
+
+    if [ "$agent_flavor" == "datadog-fips-agent" ]; then
+        remove_existing_packages_for_fips_flavor "$sudo_cmd" "$OS" "$DISTRIBUTION"
+    fi
 
     echo -e "  \033[33mInstalling package(s): ${packages[*]}\n\033[0m"
 
@@ -1417,7 +1430,10 @@ elif [ "$OS" == "SUSE" ]; then
     # Install the installer
     # Note: this function will remove installed packages from the "packages" array
     install_installer "$sudo_cmd" "$OS" "$DISTRIBUTION" "$DD_INSTALLER" "$DD_REMOTE_UPDATES" "$DD_APM_INSTRUMENTATION_ENABLED" "packages" || true
-    remove_existing_packages_for_fips_flavor "$sudo_cmd" "$OS" "$DISTRIBUTION"
+
+    if [ "$agent_flavor" == "datadog-fips-agent" ]; then
+        remove_existing_packages_for_fips_flavor "$sudo_cmd" "$OS" "$DISTRIBUTION"
+    fi
 
   if [ ${#packages[@]} -ne 0 ]; then
     echo -e "  \033[33mInstalling package(s): ${packages[*]}\n\033[0m"
@@ -1777,6 +1793,12 @@ if [ ! "$no_agent" ]; then
   $sudo_cmd chmod 640 "$config_file"
 fi
 
+# set the FIPS configuration
+if [ -n "$fips_mode" ]; then
+  ensure_config_file_exists "$sudo_cmd" "$config_file_fips" "dd-agent"
+  # TODO: set port range in file, or environment variable
+fi
+
 # set the system-probe configuration
 if [ -n "$system_probe_ensure_config" ]; then
   ensure_config_file_exists "$sudo_cmd" "$system_probe_config_file" "root"
@@ -1833,6 +1855,11 @@ if [ ! "$no_agent" ] && ! is_installed_by_installer "$sudo_cmd" "datadog-agent";
   $sudo_cmd sh -c "exec cat > $etcdir/install_info " <<EOF
 $install_info_content
 EOF
+fi
+
+if [ -n "$fips_mode" ]; then
+  # Creating or overriding the install information
+  $sudo_cmd sh -c "echo '$install_info_content' > $etcdirfips/install_info"
 fi
 
 # On SUSE 11, sudo service datadog-agent start fails (because /sbin is not in a base user's path)
