fix(missing): allow error log file to be empty or non-existant

diff --git a/install_script.sh.template b/install_script.sh.template
--- a/install_script.sh.template
+++ b/install_script.sh.template
@@ -169,6 +169,7 @@ function on_error() {
 
     printf "\033[31m$ERROR_MESSAGE
 It looks like you hit an issue when trying to install the $nice_flavor.
+    
     $ERR_SUMMARY
 
 Troubleshooting and basic usage information for the $nice_flavor are available at:
@@ -772,8 +773,8 @@ if [ "$OS" == "RedHat" ]; then
     echo -e "  \033[33mInstalling package(s): ${packages[*]}\n\033[0m"
 
     $sudo_cmd yum -y --disablerepo='*' --enablerepo='datadog' install $dnf_flag "${packages[@]}" || $sudo_cmd yum -y install $dnf_flag "${packages[@]}" 2>"/tmp/ddog_install_error_msg"
-    cat "/tmp/ddog_install_error_msg"
-    ERR_SUMMARY=$(grep "Error Summary" -A3 /tmp/ddog_install_error_msg | echo "")
+    cat "/tmp/ddog_install_error_msg" || true
+    ERR_SUMMARY=$(grep "Error Summary" -A3 /tmp/ddog_install_error_msg || true)
 
 elif [ "$OS" == "Debian" ]; then
     apt_trusted_d_keyring="/etc/apt/trusted.gpg.d/datadog-archive-keyring.gpg"
@@ -891,8 +892,8 @@ If the cause is unclear, please contact Datadog support.
     echo -e "  \033[33mInstalling package(s): ${packages[*]}\n\033[0m"
 
     $sudo_cmd apt-get install -y --force-yes "${packages[@]}" 2>"/tmp/ddog_install_error_msg"
-    cat "/tmp/ddog_install_error_msg"
-    ERR_SUMMARY=$(grep "Error Summary" -A3 /tmp/ddog_install_error_msg | echo "")
+    cat "/tmp/ddog_install_error_msg" || true
+    ERR_SUMMARY=$(grep "Error Summary" -A3 /tmp/ddog_install_error_msg || true)
 
     ERROR_MESSAGE=""
 elif [ "$OS" == "SUSE" ]; then
@@ -1040,13 +1041,13 @@ elif [ "$OS" == "SUSE" ]; then
 
   if [ -z "$sudo_cmd" ]; then
     ZYPP_RPM_DEBUG="${ZYPP_RPM_DEBUG:-0}" zypper --non-interactive install "${packages[@]}" 2>"/tmp/ddog_install_error_msg" ||:
-    cat "/tmp/ddog_install_error_msg"
+    cat "/tmp/ddog_install_error_msg" || true
   else
     $sudo_cmd ZYPP_RPM_DEBUG="${ZYPP_RPM_DEBUG:-0}" zypper --non-interactive install "${packages[@]}" 2>"/tmp/ddog_install_error_msg" ||:
-    cat "/tmp/ddog_install_error_msg"
+    cat "/tmp/ddog_install_error_msg" || true
   fi
 
-   ERR_SUMMARY=$(grep "Error Summary" -A3 /tmp/ddog_install_error_msg | echo "")
+   ERR_SUMMARY=$(grep "Error Summary" -A3 /tmp/ddog_install_error_msg || true)
 
   # If zypper fails to refresh a random repo, it installs the package, but then fails
   # anyway. Therefore we let it do its thing and then see if curl was installed or not.
