Add unit test step and UT for install_script

diff --git a/install_script.sh.template b/install_script.sh.template
--- a/install_script.sh.template
+++ b/install_script.sh.template
@@ -249,9 +249,12 @@ function ensure_config_file_exists() {
         return 1
     else
         $sudo_cmd cp "$config_file.example" "$config_file"
+        cp_res=$?
         $sudo_cmd chown "$owner:dd-agent" "$config_file"
+        chown_res=$?
         $sudo_cmd chmod 640 "$config_file"
-        return 0
+        chmod_res=$?
+        return $((cp_res + chown_res + chmod_res))
     fi
 }
 
@@ -1078,36 +1081,48 @@ if [ -n "$upgrade" ] && [ "$agent_flavor" != "datadog-dogstatsd" ]; then
 fi
 
 # Set the configuration
-if [ -e "$config_file" ] && [ -z "$upgrade" ]; then
-  printf "\033[34m\n* Keeping old $config_file configuration file\n\033[0m\n"
-elif [ ! "$no_agent" ]; then
-  if ensure_config_file_exists "$sudo_cmd" "$config_file" "dd-agent"; then
-    if [ -n "$apikey" ]; then
-      printf "\033[34m\n* Adding your API key to the $nice_flavor configuration: $config_file\n\033[0m\n"
-      $sudo_cmd sh -c "sed -i 's/api_key:.*/api_key: $apikey/' $config_file"
-    else
-      # If the import script failed for any reason, we might end here also in case
-      # of upgrade, let's not start the agent or it would fail because the api key
-      # is missing
-      if ! $sudo_cmd grep -q -E '^api_key: .+' "$config_file"; then
-        printf "\033[31mThe $nice_flavor won't start automatically at the end of the script because the Api key is missing, please add one in datadog.yaml and start the $nice_flavor manually.\n\033[0m\n"
-        no_start=true
-      fi
+# Unit method
+function update_api_key() {
+  local sudo_cmd="$1"
+  local apikey="$2"
+  local config_file="$3"
+  if [ -n "$apikey" ]; then
+    printf "\033[34m\n* Adding your API key to the $nice_flavor configuration: $config_file\n\033[0m\n"
+    $sudo_cmd sh -c "sed -i 's/api_key:.*/api_key: $apikey/' $config_file"
+  else
+    # If the import script failed for any reason, we might end here also in case
+    # of upgrade, let's not start the agent or it would fail because the api key
+    # is missing
+    if ! $sudo_cmd grep -q -E '^api_key: .+' "$config_file"; then
+      printf "\033[31mThe $nice_flavor won't start automatically at the end of the script because the Api key is missing, please add one in datadog.yaml and start the $nice_flavor manually.\n\033[0m\n"
+      no_start=true
     fi
-
-    if [ -z "$fips_mode" ]; then
-      if [ -n "$site" ]; then
-        printf "\033[34m\n* Setting SITE in the $nice_flavor configuration: $config_file\n\033[0m\n"
-        $sudo_cmd sh -c "sed -i 's/^# site:.*$/site: $site/' $config_file"
-      fi
-      if [ -n "$DD_URL" ]; then
-        printf "\033[34m\n* Setting DD_URL in the $nice_flavor configuration: $config_file\n\033[0m\n"
-        $sudo_cmd sh -c "sed -i 's/^# dd_url:.*$/dd_url: $DD_URL/' $config_file"
-      fi
-    else
-      printf "\033[34m\n* Setting $nice_flavor configuration to use FIPS proxy: $config_file\n\033[0m\n"
-      $sudo_cmd cp "$config_file" "${config_file}.orig"
-      $sudo_cmd sh -c "exec cat - '${config_file}.orig' > '$config_file'" <<EOF
+  fi
+}
+function update_site() {
+  local sudo_cmd="$1"
+  local site="$2"
+  local config_file="$3"
+  if [ -n "$site" ]; then
+    printf "\033[34m\n* Setting SITE in the $nice_flavor configuration: $config_file\n\033[0m\n"
+    $sudo_cmd sh -c "sed -i 's/^# site:.*$/site: $site/' $config_file"
+  fi
+}
+function update_url() {
+  local sudo_cmd="$1"
+  local url="$2"
+  local config_file="$3"
+  if [ -n "$url" ]; then
+    printf "\033[34m\n* Setting DD_URL in the $nice_flavor configuration: $config_file\n\033[0m\n"
+    $sudo_cmd sh -c "sed -i 's/^# dd_url:.*$/dd_url: $url/' $config_file"
+  fi
+}
+function update_fips() {
+  local sudo_cmd="$1"
+  local config_file="$2"
+  printf "\033[34m\n* Setting $nice_flavor configuration to use FIPS proxy: $config_file\n\033[0m\n"
+  $sudo_cmd cp "$config_file" "${config_file}.orig"
+  $sudo_cmd sh -c "exec cat - '${config_file}.orig' > '$config_file'" <<EOF
 # Configuration for the agent to use datadog-fips-proxy to communicate with Datadog via FIPS-compliant channel.
 
 fips:
@@ -1115,40 +1130,67 @@ fips:
     port_range_start: 9803
     https: false
 EOF
-    fi
-    if [ -n "$hostname" ]; then
-      printf "\033[34m\n* Adding your HOSTNAME to the $nice_flavor configuration: $config_file\n\033[0m\n"
-      $sudo_cmd sh -c "sed -i 's/^# hostname:.*$/hostname: $hostname/' $config_file"
-    fi
-    if [ -n "$host_tags" ]; then
-        printf "\033[34m\n* Adding your HOST TAGS to the $nice_flavor configuration: $config_file\n\033[0m\n"
-        formatted_host_tags="['""$( echo "$host_tags" | sed "s/,/','/g" )""']"  # format `env:prod,foo:bar` to yaml-compliant `['env:prod','foo:bar']`
-        $sudo_cmd sh -c "sed -i \"s/^# tags:.*$/tags: ""$formatted_host_tags""/\" $config_file"
-    fi
+}
+function update_hostname(){
+  local sudo_cmd="$1"
+  local hostname="$2"
+  local config_file="$3"
+  if [ -n "$hostname" ]; then
+    printf "\033[34m\n* Adding your HOSTNAME to the $nice_flavor configuration: $config_file\n\033[0m\n"
+    $sudo_cmd sh -c "sed -i 's/^# hostname:.*$/hostname: $hostname/' $config_file"
   fi
-  if [ -n "$dd_env" ]; then
-    printf "\033[34m\n* Adding your DD_ENV to the $nice_flavor configuration: $config_file\n\033[0m\n"
-    $sudo_cmd sh -c "sed -i 's/^# env:.*/env: $dd_env/' $config_file"
+}
+function update_hosttags(){
+  local sudo_cmd="$1"
+  local host_tags="$2"
+  local config_file="$3"
+  if [ -n "$host_tags" ]; then
+      printf "\033[34m\n* Adding your HOST TAGS to the $nice_flavor configuration: $config_file\n\033[0m\n"
+      formatted_host_tags="['""$( echo "$host_tags" | sed "s/,/', '/g" )""']"  # format `env:prod,foo:bar` to yaml-compliant `['env:prod','foo:bar']`
+      $sudo_cmd sh -c "sed -i \"s/^# tags:.*$/tags: ""$formatted_host_tags""/\" $config_file"
   fi
-
-  if [ "$DD_RUNTIME_SECURITY_CONFIG_ENABLED" == "true" ]; then
-    if ensure_config_file_exists "$sudo_cmd" "$system_probe_config_file" "root"; then
-      printf "\033[34m\n* Enabling runtime security in system_probe configuration\n\033[0m\n"
-      $sudo_cmd sh -c "sed -i 's/^#\s*runtime_security_config:$/runtime_security_config:/' $security_agent_config_file $system_probe_config_file"
-    fi
-
-    if ensure_config_file_exists "$sudo_cmd" "$security_agent_config_file" "root"; then
-      printf "\033[34m\n* Enabling runtime security in security_agent configuration\n\033[0m\n"
-      $sudo_cmd sh -c "sed -i '/^runtime_security_config:/,// s/\(\s\+\)#\s*enabled:\s*false/\1enabled: true/' $security_agent_config_file $system_probe_config_file"
-    fi
+}
+function update_runtime_security(){
+  local sudo_cmd="$1"
+  local security_config="$2"
+  local local_config_file="$3"
+  if [ "$security_config" == "true" ]; then
+    printf "\033[34m\n* Enabling runtime security in $(basename $local_config_file) configuration\n\033[0m\n"
+    $sudo_cmd sh -c "sed -i 's/^#\s*runtime_security_config:$/runtime_security_config:/' $local_config_file"
+    $sudo_cmd sh -c "sed -i '/^runtime_security_config:/,// s/\(\s\+\)#\s*enabled:\s*false/\1enabled: true/' $local_config_file"
   fi
-
-  if [ "$DD_COMPLIANCE_CONFIG_ENABLED" == "true" ]; then
-    if ensure_config_file_exists "$sudo_cmd" "$security_agent_config_file" "root"; then
-      printf "\033[34m\n* Enabling compliance monitoring in security_agent configuration\n\033[0m\n"
-      $sudo_cmd sh -c "sed -i 's/^#\s*compliance_config:$/compliance_config:/' $security_agent_config_file"
-      $sudo_cmd sh -c "sed -i '/^compliance_config:/,// s/\(\s\+\)#\s*enabled:\s*false/\1enabled: true/' $security_agent_config_file"
+}
+function update_compliance_configuration(){
+  local sudo_cmd="$1"
+  local compliance_config="$2"
+  local local_config_file="$3"
+  if [ "$compliance_config" == "true" ]; then
+    printf "\033[34m\n* Enabling compliance monitoring in $(basename $local_config_file) configuration\n\033[0m\n"
+    $sudo_cmd sh -c "sed -i 's/^#\s*compliance_config:$/compliance_config:/' $local_config_file"
+    $sudo_cmd sh -c "sed -i '/^compliance_config:/,// s/\(\s\+\)#\s*enabled:\s*false/\1enabled: true/' $local_config_file"
+  fi
+}
+# "Main" configuration update
+if [ -e "$config_file" ] && [ -z "$upgrade" ]; then
+  printf "\033[34m\n* Keeping old $config_file configuration file\n\033[0m\n"
+elif [ ! "$no_agent" ]; then
+  if ensure_config_file_exists "$sudo_cmd" "$config_file" "dd-agent"; then
+    update_api_key "$sudo_cmd" "$apikey" "$config_file"
+    if [ -z "$fips_mode" ]; then
+      update_site "$sudo_cmd" "$site" "$config_file"
+      update_url "$sudo_cmd" "$DD_URL" "$config_file"
+    else
+      update_fips "$sudo_cmd" "$config_file"
     fi
+    update_hostname "$sudo_cmd" "$hostname" "$config_file"
+    update_hosttags "$sudo_cmd" "$host_tags" "$config_file"
+  fi
+  if ensure_config_file_exists "$sudo_cmd" "$security_agent_config_file" "root"; then;
+    update_runtime_security "$sudo_cmd" "$DD_RUNTIME_SECURITY_CONFIG_ENABLED" "$security_agent_config_file"
+    update_compliance_configuration "$sudo_cmd" "$DD_RUNTIME_SECURITY_CONFIG_ENABLED" "$security_agent_config_file"
+  fi
+  if ensure_config_file_exists "$sudo_cmd" "$system_probe_config_file" "root"; then;
+    update_runtime_security "$sudo_cmd" "$DD_RUNTIME_SECURITY_CONFIG_ENABLED" "$system_probe_config_file"
   fi
 fi
 
