feat: change error code when using version under 7.41 for FIPS + add an error when asking for FIPS mode on non x86_64 architecture
Signed-off-by: Nicolas Guerguadj <nicolas.guerguadj@epita.fr>

diff --git a/install_script.sh.template b/install_script.sh.template
--- a/install_script.sh.template
+++ b/install_script.sh.template
@@ -496,12 +496,21 @@ if [[ "$agent_flavor" == "datadog-dogstatsd" ]]; then
     fi
 fi
 
-if [ -n "$fips_mode" ] && { [[ -n "$agent_minor_version_without_patch" ]] && [[ "${agent_minor_version_without_patch%.*}" -lt 41 ]]; }; then
-    ERROR_MESSAGE="FIPS mode is only available since version AGENT_MAJOR_VERSION_PLACEHOLDER.41.0 and requested minor version is $agent_minor_version"
-    ERROR_CODE=$UNSUPPORTED_PLATFORM_CODE
-    printf "\033[31m$ERROR_MESSAGE\033[0m\n"
-    report_telemetry
-    exit 1;
+if [ -n "$fips_mode" ]; then
+    if [[ `uname -m` != "x86_64" ]]; then
+        ERROR_MESSAGE="FIPS mode isn't available for your architecture"
+        ERROR_CODE=$UNSUPPORTED_PLATFORM_CODE
+        printf "\033[31m$ERROR_MESSAGE\033[0m\n"
+        report_telemetry
+        exit 1;
+    fi
+    if [[ -n "$agent_minor_version_without_patch" ]] && [[ "${agent_minor_version_without_patch%.*}" -lt 41 ]]; then
+        ERROR_MESSAGE="FIPS mode is only available since version AGENT_MAJOR_VERSION_PLACEHOLDER.41.0 and requested minor version is $agent_minor_version"
+        ERROR_CODE=$INVALID_PARAMETERS_CODE
+        printf "\033[31m$ERROR_MESSAGE\033[0m\n"
+        report_telemetry
+        exit 1;
+    fi
 fi
 
 # Root user detection
